### PR TITLE
Fix The Styling of Markdown Files under 'docs' folder and its sub-folders, among other things as well

### PR DESCRIPTION
**Pull request by og-mrk**
### Changes made to to the Markdown files are the following:
  1. Add a \<div\> attribute to every screenshot, with its \<figure\> and \<figcaption\> attributes inside said \<div\> So I can align all elements inside the \<div\> to be center aligned.
  2. Made all paragraph elements inside \<figcaption\> attribute to be Italic using the \<i\> attribute.
  3. Added some paragraphs to some of the empty \<figcaption\> attributes.
  4. Made the Heading Levels generally bigger to make the reading experience better and clear-er. or in other words, heading level 3 became level 2, heading level 4 became 3, and so on...
  5. Fixed the Hint Icons in every Markdown file that uses them, And used Github's Supported way of doing it, for example:
     ```
     > [!NOTE]
     > This is a side note.

     > [!WARNING]
     > Warning User!
     ```
     The full list I've used is found in this discussion post on Github: https://github.com/orgs/community/discussions/16925
  6. All of the Markdown Files has the above edits applied, Except The 'releases.md' file under the 'releases' folder.

### CODE REVIEW

**Comment by PavelLaptev** [comment]
@og-mrk, thanks a bunch for the PR! Loads of cool changes.

Quick question: why do we need to wrap up <figure> into a <div>? Noticed GitBook does it automatically (check out the screenshot). Is it to make it look nicer on GitHub?

image

**Comment by og-mrk** [comment]
I've force-pushed an Amended Commit removing the \<div\>\</div\> for one of the Screenshots, so I can see as well if it works **_without_** the \<div\> container, and the \<figure\>\</figure\> center aligns well when we use `align="center"`, but the Paragraph doesn't Center Align, **_Markdown Text & Preview is visible in the screenshots below_**.

### Screenshots
image
<div align="center">
<p><i>The Markdown Text</i></p>
</div>

<hr>

image
<div align="center">
<p><i>Preview for Markdown Text, with some Highlighting in Red Text/Lines added by me.</i></p>
</div>

**Comment by og-mrk** [comment]
Hello @PavelLaptev ,

> Noticed GitBook does it automatically (check out the screenshot). Is it to make it look nicer on GitHub?
> 
> image

The answer to your question is yes, it was changed to make it look nicer on GitHub.

**Comment by PavelLaptev** [comment]
Thanks @og-mrk! looks good 🙂  Could you resolve merge conflicts?

**Comment by og-mrk** [comment]
Fixed Merge Conflicts @PavelLaptev 😄

**Comment by PavelLaptev** [comment]
Thank you @og-mrk!

**Pull request merged**
